pipeline {
    agent any
    tools {
        maven 'maven-3.9'
    }
    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev','staging','prod'], description: 'target environment')
        booleanParam(name: 'SKIP_TESTS', defaultValue: false, description: 'Skip the test stage')
    }
    ennvironment {
        MY_SECRET = credentials('my-secret')
    }
    stages {
        stage('print secrets') {
            steps {
                echo "MY_SECRET: ${MY_SECRET}"
                sh "Unmasked ${MY_SECRET}"
                withCredentials([string(credentialsId: 'toby_peel', variable: 'PASSWORD')]) {
                    echo "PASSWORD: ${PASSWORD}"
                    sh "echo unmasked ${PASSWORD}"
                }
            }
        }
        stage('Compile') {
            steps { sh 'mvn -B clean compile' }
        }
        stage('Test') {
            when {
                expression { return !params.SKIP_TESTS }
            }
            steps {
                sh 'mvn -B test'
            }
            post {
                always { junit 'target/surefire-reports/*.xml' }
            }
        }
        stage('Package') {
            steps {
                echo "packaging the application for ${params.ENVIRONMENT} environment"
                sh 'mvn -B package -DskipTests'
             }
        }

       stage('Deploy') {
            when { branch 'master' }
            steps {
                echo "Deploying the application to ${params.ENVIRONMENT} environment"
            }
        }
    }
    post {
            success {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
}