pipeline {
    agent any
    tools {
        maven 'maven-3.9'
    }
    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev','staging','prod'], description: 'target environment')
        booleanParam(name: 'SKIP_TESTS', defaultValue: false, description: 'Skip the test stage')
    }
    stages {
        stage('Compile') {
            steps { sh 'mvn -B clean compile' }
        }
        stage('Test') {
            when {
                expression { return !params.SKIP_TESTS }
            }
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                    timeout(time: 2, unit: 'SECONDS') {
                        sh 'Sleeping for five seconds to simulate a long-running test...'
                        sleep 5
                    }
                }
                sh 'mvn -B test'
                retry(3) {
                    sh '''
                    echo 'Rolling the dice to simulate flaky tests...'
                    ROLL=$(shuf -i 1-100 -n 1)
                    echo "Rolled: $ROLL"
                    test "$ROLL" -gt 50
                    '''
                }
            }

            post {
                always { junit 'target/surefire-reports/*.xml' }
            }
        }
        stage('Package') {
            steps {
                echo "packaging the application for ${params.ENVIRONMENT} environment"
                sh 'mvn -B package -DskipTests'
             }
        }

       stage('Deploy') {
            when { branch 'master' }
            steps {
                echo "Deploying the application to ${params.ENVIRONMENT} environment"
            }
        }
    }
    post {
            success {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
}